# No copyright. Vladislav Aleinik, 2023

#===============================#
# List of tests for the problem #
#===============================#

# List of tests for current problem:
TESTS=# None

# Include common Makefile:
include ../../common.mk
