# Copyright 2024 Vladislav Aleinik

#===============================#
# List of tests for the problem #
#===============================#

# List of tests for current problem:
TESTS = \
	timing \
	overshift

# Include common Makefile:
include ../../common.mk
