# Copyright 2024 Vladislav Aleinik

#===============================#
# List of tests for the problem #
#===============================#

# List of tests for current problem:
TESTS = \
	stack-overflow-gen

tests/stack-overflow-gen.input: FORCE
	@mkdir -p tests
	@echo 100000 > $@

# Include common Makefile:
include ../../common.mk
